pyspark_ai/code_logger.py

Hi Team,
It's better to limit the logger handler to one per session. As user might want to use multiple llm in a single session.
Currently that would result in multiple same logs printed on the console.
Code Block:
`from pyspark_ai import SparkAI
spark_ai=SparkAI(verbose=True)
spark_ai=SparkAI(verbose=True)
spark_ai=SparkAI(verbose=True)
spark_ai.activate()`
Limiting the handler will result in just one log.

Modify logger handler limit to one per session

---

README.md
examples/example.ipynb

This pull request updates the README.md file to include links to a detailed blog post and a demo video in the "Introduction" section. 
The intention is to provide users with additional resources to understand and utilize our project effectively. The blog post offers a comprehensive walkthrough, and the video features a project announcement along with a practical demonstration. 
Changes include:
- Added an "Introduction" section with a brief overview of the project.
- Listed two key resources (blog post and video) with appropriate descriptions.

Add Blog Post and Demo Video Links to README

---

README.md
examples/example.ipynb

Since GPT-4 is GA now https://openai.com/blog/gpt-4-api-general-availability, let's simplify README and Example notebook and create SparkAI without parameters in the example code

Simplify README since GPT-4 is now GA

---

examples/example.ipynb
pyspark_ai/pyspark_ai.py

https://github.com/databrickslabs/pyspark-ai/issues/63
When PySpark version is below 3.4.0 and Spark connect is not available, there will be import error.
This PR adds a try/except to avoid the issue.

Fix backward compatibility when PySpark version < 3.4.0

---

pyspark_ai/pyspark_ai.py

When Python code is evaluated, currently it uses plain `exec()` calls. This patch improves the system by wrapping the `exec()` call with a `try-except` block and wrapping the generated code with a `compile()` call. This will give better error messages.
For example using compile with a virtual filename lets the user better identify where the errors come from.
```
❯ python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 19 2020, 20:48:48)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> compile("false", "Pyspark", "exec")
<code object <module> at 0x7faa281253b0, file "Pyspark", line 1>
>>> exec(compile("false", "Pyspark", "exec"))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
--> File …
```

[Minor] Improve error messages for codegen

---

pyspark_ai/tool.py

In the latest v0.1.11 release, there is the following error when using Spark connect:
```
ValidationError: 1 validation error for QuerySparkSQLTool
spark
instance of SparkSession expected (type=type_error.arbitrary_type; expected_arbitrary_type=SparkSession)
```
This PR is to fix it.
We should have GA test later.

Fix regression of errors when using Spark connect

---

examples/window.ipynb
pyspark_ai/ai_utils.py
pyspark_ai/pyspark_ai.py
pyspark_ai/tool.py

The input of the tool `QueryValidationTool` can contain 3 backticks ``` and the tool QueryValidationTool will throw syntax error if the input has 3 backticks
This PR is to fix by using the method `extract_code_blocks` before checking the query. It also introduce a new SQL transform example for the blog https://www.databricks.com/blog/2015/07/15/introducing-window-functions-in-spark-sql.html

Fix backticks error in QueryValidationTool

---

poetry.lock
pyproject.toml

This PR align the Pandas and GRPC version with Apache Spark https://github.com/apache/spark/blob/master/python/setup.py#L133
The current pandas version of "2.0.2" is too high and Apache Spark doesn't support such pandas version. 
After changes,  it is  easier to use Pyspark-ai in conjunction with other packages.

Align Pandas and GRPC version with Apache Spark

---

pyspark_ai/prompt.py
tests/test_spark_ai.py

Aggregate the PySpark DataFrame before converting it to a Pandas DataFrame. This helps reduce the likelihood of an OOM error when the PySpark DataFrame is too large to fit into memory.
Unit test.
A manual run in console is as shown below:
```py
>>> from pyspark_ai import SparkAI
>>> spark_ai = SparkAI(verbose=True)
>>> spark_ai.activate()
>>> df = spark_ai.create_df("https://www.carpro.com/blog/full-year-2022-national-auto-sales-by-brand")
...
>>> root_logger = logging.getLogger()
>>> log_capture_string = StringIO()
>>> ch = logging.StreamHandler(log_capture_string)
>>> root_logger.addHandler(ch)
>>> df.ai.plot("pie chart for US sales market shares, show the top 5 brands and the sum of others")
...
>>> log_contents = log_capture_string.getvalue()
>>> log_contents.find("groupBy")  # …
```

Aggregate PySpark DataFrame before Pandas conversion

---

.gitignore
benchmark/wikisql/wiki_sql.py
pyspark_ai/prompt.py
pyspark_ai/pyspark_ai.py
tests/test_spark_ai.py

For the `df.ai.transform` method, if the input dataframe is reading from a single table, include the table comment into the prompt can help the accuracy of generated SQL.
Before the changes, the following WikiSQL tests
```
{"phase": 1, "table_id": "1-1004033-1", "question": "When did the Metrostars have their first Rookie of the Year winner?", "sql": {"sel": 0, "conds": [[4, 0, "MetroStars"]], "agg": 2}, "result": [2001.0], "query": "SELECT MIN(col0) AS result FROM table_1_1004033_1 WHERE col4 = 'metrostars'"}
{"phase": 1, "table_id": "1-1004033-1", "question": "What college did the Rookie of the Year from the Columbus Crew attend?", "sql": {"sel": 7, "conds": [[4, 0, "Columbus Crew"]], "agg": 0}, "result": ["virginia"], "query": "SELECT col7 AS result FROM table_1_1004033_1 WHERE col4 = …
```

Add table comment to the prompt of DataFrame transform

---

benchmark/wikisql/wiki_sql.py
pyspark_ai/prompt.py
pyspark_ai/pyspark_ai.py

This PR adds a similarity function that uses the spacy library to calculate semantic similarity between string results. This is used in evaluating accuracy of results when run on the wikisql dataset.
The PR also makes modifications to fix examples that use COUNT, such as the following questions (no longer fail):
```
Question: what's the total number of south australia with victoria value of 2173
Question: what is the total number of ties played where total w–l is 38–24
Question: what is the total number of singles w–l where doubles w–l is 11–14
```
The PR also accounts for different orderings of result lists, such as the following question (no longer fail):
```
Which wrestlers have had 2 reigns?
Expected result: ['roderick strong', 'davey richards', 'erick stevens']
Actual result: …
```

Add similarity wikisql function, fix prompt for COUNT examples

---

pyspark_ai/prompt.py

In the current SQL transform prompt, we shouldn't put "If the question contains 'total number', use the SQL function COUNT(column_name) on the relevant column(s)." to overfit the benchmark.

Avoid overfit in the prompt of SQL transformation

---

pyspark_ai/pyspark_ai.py

https://github.com/databrickslabs/pyspark-ai/issues/127
Before this PR, there is no check on whether the table comment is None. This PR fixes the issue.

Fix regression on SQL transform

---

pyspark_ai/pyspark_ai.py
tests/test_ai_tools.py

This PR excludes `SimilarValueTool` by default, if `vector_store_dir` is not configured. The change is made to ensure that we do not store vector db in-memory, as this could cause OOM.

Exclude SimilarValueTool By Default

---

docs/CNAME

As per https://www.mkdocs.org/user-guide/deploying-your-docs/#custom-domains, we need this for custom domain.

Add CNAME file for doc website

---

.github/workflows/website.yml

There's a small mistake in the GitHub Actions workflow file `.github/workflows/website.yml`. The paths filter should be nested under each event under on, not directly under on. 
https://github.com/pyspark-ai/pyspark-ai/actions/runs/6396235565:
```
[Error: .github#L1](https://github.com/pyspark-ai/pyspark-ai/commit/d0d490220343ddea7a6d02932ff26e700e6b6400#annotation_14621674381)
Invalid type for `on`
```
This PR is to fix it

Fix syntax error in .github/workflows/website.yml

---

pyspark_ai/python_executor.py
tests/test_end_to_end.py

Fix the following regression from https://github.com/pyspark-ai/pyspark-ai/pull/159:
```
>>> df.ai.plot("Bar plot of the top 5 most populous cities")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/xinrong.meng/pyspark-ai/pyspark_ai/ai_utils.py", line 66, in plot
return self.spark_ai.plot_df(self.df_instance, desc, cache)
File "/Users/xinrong.meng/pyspark-ai/pyspark_ai/pyspark_ai.py", line 525, in plot_df
plot_chain = PythonExecutor(
File "/opt/miniconda3/envs/eng_dev/lib/python3.9/site-packages/langchain/load/serializable.py", line 74, in __init__
super().__init__(**kwargs)
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PythonExecutor
logger
none is not an allowed …
```

Fix regression on the plotting API when verbose is False

---

pyspark_ai/prompt.py

This PR adds an explanation of when to use SUM vs. COUNT in the transform prompt. This fixes examples like the following:
```
Question: How many home wins occured win the road games are larger than 3.0 but road win percentage is .000?
Expected query: SELECT `(Home wins)` FROM `1-1409106-2` WHERE `Road Win Pct.` = '.000' AND `ROAD games` > 3.0
Actual query: select count(`home wins`) from `spark_ai_temp_view_1928808132` where `road games` > 3.0 and `road win pct.` = '.000'
Expected result: ['0.0']
Actual result: ['1']
```

Add explanation of when to use SUM

---

pyspark_ai/prompt.py
pyspark_ai/pyspark_ai.py
pyspark_ai/spark_sql_chain.py
tests/test_end_to_end.py

Currently, the SDK is using a ReAct agent for DataFrame transform, which requires the output format to be of the following format:
```
Thought: Spark SQL does not support dynamic pivot operations, which are required to transpose the table as requested. I should get all the distinct values of column product.
Action: query_sql_db
Action Input: "SELECT DISTINCT product FROM spark_ai_temp_view_096b0f"
Observation: [('Normal',), ('Mini',), ('Foldable',), ('Pro',), ('Pro Max',)]
```
This doesn't work well when the LLM is not GPT-4. From time to time, there can be parse exceptions. For example: https://github.com/pyspark-ai/pyspark-ai/issues/118
So, to make sure the API `df.ai.transform` generate robust code on non-gpt-4 models, we can follow https://github.com/pyspark-ai/pyspark-ai/pull/159 and …

DataFrame transform: use simple code generation when LLM is not GPT-4

---

poetry.lock
pyproject.toml

Fix dependency groups by including all extras under tool.poetry.dependencies. Ensures that pip installation of groups works correctly
Tested using virtual environments

Fix dependency groups for pip install

---

README.md

Remove README.md examples other than `transform` and `plot` to improve readability

Condense README examples

---

tests/test_ai_tools.py

This PR skips `test_transform_without_similar_value_tool` (nondeterministic behavior) for later investigation

Skip test for transform without similar_value

---

tests/test_end_to_end.py

As per https://github.com/pyspark-ai/pyspark-ai/actions/runs/6724412827/job/18276616088, the end-to-end test case is becoming unstable.

Ignore unstable end-to-end case test_laplace_random_udf

---

tests/test_end_to_end.py

The wikisql end-to-end tests becomes unstable on gpt-3.5-turbo: https://github.com/pyspark-ai/pyspark-ai/actions/runs/6724764580/job/18277726463

Run wikisql end-to-end tests on GPT-4 only

---

tests/test_end_to_end.py

The test case test_array_udf_output becomes unstable as per https://github.com/pyspark-ai/pyspark-ai/actions/runs/6724764580/job/18277726463

Ignore end-to-end test case test_array_udf_output 

---

poetry.lock
pyproject.toml
pyspark_ai/pyspark_ai.py

Include all optional dependencies in `[all]` group to support `pip install pyspark-ai[all]`
Test with: `pip install 'pyspark-ai[all] @ git+https://github.com/asl3/pyspark-ai.git@add-all-dependency-group'`

Add pyspark-ai[all] group for pip install

---

pyproject.toml

We restore v0.1.16 as v0.1.18 in the previous release.
With many enhancement in the latest master, it is time to release v0.1.19

Bump version to v0.1.19

---

pyspark_ai/pyspark_ai.py
pyspark_ai/spark_utils.py
tests/test_python_executor.py
tests/test_spark_ai.py

Also PR includes corresponding updates of tests. Because SparkUtils is a part of a public API I added missing doc strings for moved methods.
modified:   pyspark_ai/pyspark_ai.py
modified:   pyspark_ai/spark_utils.py
modified:   tests/test_python_executor.py
modified:   tests/test_spark_ai.py
Close #108

Move all spark-related method to SparkUtils
